when@prod: &prod
framework:
    session:
        handler_id: "%env(REDIS_SESSION_URL)%/%env(int:REDIS_SESSION_DATABASE)%"
    cache:
        app: cache.adapter.redis
        system: cache.adapter.redis
        default_redis_provider: "%env(REDIS_CACHE_URL)%/%env(int:REDIS_CACHE_DATABASE)%"
when@dev: *prod
