framework:
    messenger:
        failure_transport: failed
        transports:
            async:
                dsn: "%env(string:REDIS_SESSION_URL)%"
                options:
                    stream: async
            low_priority:
                dsn: "%env(string:REDIS_SESSION_URL)%"
                options:
                    stream: low_priority
            high_priority:
                dsn: "%env(string:REDIS_SESSION_URL)%"
                options:
                    stream: high_priority
            failed: "doctrine://default?queue_name=failed"

        # Send mails over Message Queue
        routing:
            'Symfony\Component\Mailer\Messenger\SendEmailMessage': high_priority
