default:
  interruptible: true
  tags:
    - bsc-hetzner-x86

# Child pipelines are used here to prevent problems when multiple plugins exist in the project.
# By using triggers the plugin Pipelines run independently and their variables
# (like PLUGIN_NAME) do not override each other.
plugins-template-theme:
    trigger:
        include: '/custom/static-plugins/TemplateTheme/.gitlab-ci.yml'
        strategy: depend
