services:
    shopware:
        image: 'dockware/dev:6.6.4.0'
        container_name: 'shopware'
        ports:
            - "80:80"       # Webserver / Apache
            - "3306:3306"   # MySQL database
            # - "22:22"       # SSH
            - "8888:8888"   # Admin watcher
            - "9999:9999"   # Storefront watcher (background)
            - "9998:9998"   # Storefront watcher (background)
        networks:
            - 'web'
        environment:
            - 'XDEBUG_ENABLED=0'
            - 'PHP_VERSION=8.2'
            - 'OPENSEARCH_URL=http://opensearch:9200'
            - 'SHOPWARE_ES_ENABLED=1'
            - 'SHOPWARE_ES_INDEXING_ENABLED=1'
            - 'SHOPWARE_ES_INDEX_PREFIX=sw'
            - 'SHOPWARE_ES_THROW_EXCEPTION=1'

        volumes:
            - "./.env:/var/www/html/.env"
            - "./custom/static-plugins:/var/www/html/custom/static-plugins"
            - "./composer.json:/var/www/html/composer.json"
            - "./composer.lock:/var/www/html/composer.lock"
            - "./auth.json:/var/www/html/auth.json"
            - "./config/customFields:/var/www/html/config/customFields"

            - "./config/packages/dev:/var/www/html/config/packages/dev"
            - "./config/packages/prod:/var/www/html/config/packages/prod"
            - "./config/packages/elasticsearch.yaml:/var/www/html/config/packages/elasticsearch.yaml"
            - "./config/packages/lock.yaml:/var/www/html/config/packages/lock.yaml"
            - "./config/packages/mailer.yaml:/var/www/html/config/packages/mailer.yaml"
            - "./config/packages/shopware.yaml:/var/www/html/config/packages/shopware.yaml"
            - "./config/packages/cache.yaml:/var/www/html/config/packages/cache.yaml"
            - "./config/bundles.php:/var/www/html/config/bundles.php"

            - "./config/services_dockware.yaml:/var/www/html/config/services.yaml"
            - "./Makefile:/var/www/html/Makefile"
            - "./fixtures:/var/www/html/src/Fixtures"
            - "./scripts:/var/www/html/scripts"
            - "db:/var/lib/mysql"
            - "vendor:/var/www/html/vendor"

    opensearch:
        image: "opensearchproject/opensearch:2"
        restart: 'unless-stopped'
        container_name: 'opensearch'
        networks:
            - 'web'
        ports:
            - "9200:9200"
        environment:
            - 'EA_JAVA_OPTS=-Xms512m -Xms512m'
            - 'discovery.type=single-node'
            # we don't need security features for local development
            - 'plugins.security.disabled=true'
            - 'OPENSEARCH_INITIAL_ADMIN_PASSWORD=jdoSdf24%%'
        volumes:
            - "opensearch:/usr/share/opensearch/data"

    redis-session:
        image: 'redis:6'
        container_name: 'redis-session'
        networks:
            - 'web'
        ports:
            - "6379:6379"
        volumes:
            - "redis-session:/data"

    redis-cache:
        image: 'redis:6'
        container_name: 'redis-cache'
        networks:
            - 'web'
        ports:
            - "6380:6379"
        volumes:
            - "redis-cache:/data"

    rabbitmq:
        image: 'rabbitmq:3-management'
        container_name: 'rabbitmq'
        networks:
            - 'web'
        ports:
            - "15672:15672"
            - "5672:5672"
        environment:
            - 'RABBITMQ_DEFAULT_USER=shopware'
            - 'RABBITMQ_DEFAULT_PASS=shopware'
        volumes:
            - "rabbitmq:/var/lib/rabbitmq"


networks:
    web:
        external: false

volumes:
    db:
        driver: local
    vendor:
        driver: local
    opensearch:
        driver: local
    redis-session:
        driver: local
    redis-cache:
        driver: local
    rabbitmq:
        driver: local
