version: '3'

services:
  shopware:
    container_name: hipay-enterprise-shopware-6
    build:
      args:
        - DOCKWARE_VERSION=6.5.8.7
      context: .
      dockerfile: bin/docker/images/shopware/Dockerfile
    ports:
      - '2001:22'
      - '3306:3306'
    networks:
      - shopware
    env_file:
      - ./bin/docker/conf/development/.env
    volumes:
      - 'shopware_data:/var/lib/mysql'
      - './src:/var/www/html/custom/plugins/HiPayPaymentPlugin/src'
      - './tests:/var/www/html/custom/plugins/HiPayPaymentPlugin/tests'
      - './reports:/var/www/html/custom/plugins/HiPayPaymentPlugin/reports'
      - './composer.json:/var/www/html/custom/plugins/HiPayPaymentPlugin/composer.json'
      - './log:/var/www/html/var/log'
  proxy:
    container_name: proxy
    image: dockware/proxy:latest
    ports:
      - '80:80'
      - '443:443'
      - '8888:8888'
      - '9999:9999'
      - '9998:9998'
      - '9997:9997'
    depends_on:
      - shopware
    networks:
      - shopware
    volumes:
      - './bin/docker/conf/nginx/proxy.conf:/etc/nginx/conf.d/proxy.conf'

volumes:
  shopware_data:
    driver: local

networks:
  shopware:
    external: false
