version: '3'

services:
  shopware:
    container_name: hipay-enterprise-shopware-6
    build:
      args:
        - DOCKWARE_VERSION=latest
      context: .
      dockerfile: bin/docker/images/shopware/Dockerfile
    ports:
      - '8076:80'
      - '3306:3306'
    networks:
      - shopware
    env_file:
      - ./bin/docker/conf/development/.env
    volumes:
      - 'shopware_data:/var/lib/mysql'
      - '.:/var/www/html/custom/plugins/HiPayPaymentPlugin/'

volumes:
  shopware_data:
    driver: local

networks:
  shopware:
    external: false