apiVersion: v1
kind: Service
metadata:
  name: shopware-service-{{ .Release.Name }}
  namespace: default
  labels:
    cd-hipay: cron-delete
spec:
  ports:
    - port: 80
      protocol: TCP
      name: web
      targetPort: 80
  selector:
    app: shopware-{{ .Release.Name }}
    tier: frontend-{{ .Release.Name }}
  type: NodePort
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingressroute-tls-{{ .Release.Name }}
  namespace: default
  labels:
    cd-hipay: cron-delete
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ .Values.shopware_url  }}`)
      kind: Rule
      priority: 1
      services:
        - name: shopware-service-{{ .Release.Name }}
          port: 80
  tls:
    certResolver: default
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingressroute-{{ .Release.Name }}
  namespace: default
  labels:
    cd-hipay: cron-delete
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`{{ .Values.shopware_url  }}`)
      kind: Rule
      priority: 1
      services:
        - name: shopware-service-{{ .Release.Name }}
          port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopware-{{ .Release.Name }}
  labels:
    app: shopware-{{ .Release.Name }}
    cd-hipay: cron-delete
spec:
  selector:
    matchLabels:
      app: shopware-{{ .Release.Name }}
      tier: frontend-{{ .Release.Name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: shopware-{{ .Release.Name }}
        tier: frontend-{{ .Release.Name }}
        cd-hipay: cron-delete
    spec:
      containers:
      - image: {{ .Values.shopware_image }}:{{ .Values.shopware_tag }}
        imagePullPolicy: Always
        name: shopware-{{ .Release.Name }}
        resources:
          requests:
            memory: "5G"
            cpu: "1200m"
        envFrom:
          - configMapRef:
              name: shopware-configmap-{{ .Release.Name }}
        ports:
          - containerPort: 80
            name: shopware
