on:
  release:
    types: [published]

jobs:
  slack_message:
    runs-on: ubuntu-latest
    steps:
      - env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: |
          SHOPWARE_VERSION="6.5"
          if [[ "${{ github.event.release.tag_name }}" == 1.* ]]; then
            SHOPWARE_VERSION="6.4"
          fi
          JSON='{ "project": "HiPay Enterprise Shopware $SHOPWARE_VERSION", "version": "${{ github.event.release.tag_name }}", "release_link": "${{ github.event.release.html_url }}", "changelog": ${{ toJSON(github.event.release.body) }} }'
          curl -X POST --data-binary "$JSON" -H "Content-Type: application/json" ${{ vars.SLACK_WEBHOOK_URL }}
